def view(result1, result2, result3,result4, count_result = None):
    print("results from gpt are : ")
    print (result1)
    print("*************")
    print("results from script are : ")
    print (result2)
    print("*************")
    print("results from gpt script are : ")
    print (result4)
    print("*************")
    print("count results are : ")
    print (count_result)
    print("*************")